// The link-preview image for each route, generated by scripts/brand.mjs.
// Longest matching prefix wins, so every /learn/* lesson shares the Learn
// card. Keys and file names are checked against public/og by the e2e suite.
export const ogCards = {
  '/': {
    src: '/og/home.png',
    alt: 'Poker Assistant beside a screenshot of the range grid, under the headline Find your leaks. Build a better game.',
  },
  '/how-it-works': {
    src: '/og/how-it-works.png',
    alt: 'Poker Assistant beside a screenshot of a hand list sorted by EV loss, under the headline From played hand to real improvement.',
  },
  '/solutions': {
    src: '/og/solutions.png',
    alt: 'Poker Assistant beside a screenshot of the installed solution packs, under the headline Start free. Keep what you buy.',
  },
  '/accuracy': {
    src: '/og/accuracy.png',
    alt: 'Poker Assistant beside a screenshot of a solved flop and its betting ladder, under the headline GTO you can trust.',
  },
  '/faq': {
    src: '/og/faq.png',
    alt: 'Poker Assistant beside a screenshot of a range grid, under the headline Straight answers before you start.',
  },
  '/learn': {
    src: '/og/learn.png',
    alt: 'Poker Assistant beside a screenshot of the practice screen, under the headline Learn the app. Learn the poker.',
  },
} as const;

export type OgCard = (typeof ogCards)[keyof typeof ogCards];

export const ogCard = (pathname: string): OgCard =>
  Object.entries(ogCards)
    .filter(([route]) => route !== '/' && pathname.startsWith(route))
    .map(([, card]) => card as OgCard)
    .at(0) ?? ogCards['/'];
